Warehouse.Web/Controllers/BalanceController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Caching.Memory;
using System.Text.Json;
using Warehouse.Domain.Entities;
using Warehouse.Domain.ViewModels.Balance;

namespace Warehouse.Web.Controllers
{
    public class BalanceController : Controller
    {
        private readonly ILogger<BalanceController> _logger;
        private readonly IMemoryCache _memoryCache;

        public BalanceController(ILogger<BalanceController> logger, IMemoryCache memoryCache)
        {
            _logger = logger;
            _memoryCache = memoryCache;
        }
        public async Task<IActionResult> Index([Bind("SelectedResources,SelectedUnits")] BalancesListViewModel balancesListView)
        {

            //UoW GetAll
            var balancesCache = _memoryCache.Get<List<Balance>>("Balances") ?? new List<Balance>();
            var resources = _memoryCache.Get<List<Resource>>("Resources")?.Where(r => r.IsActive) ?? new List<Resource>();
            var units = _memoryCache.Get<List<Unit>>("Units")?.Where(u => u.IsActive) ?? new List<Unit>();

            var balances = JsonSerializer.Deserialize<List<Balance>>(JsonSerializer.Serialize(balancesCache));

            // Фильтрация
            if (balancesListView.SelectedResources != null && balancesListView.SelectedResources.Count() > 0)
            {
                balances = balances.Where(b => balancesListView.SelectedResources.Contains(b.ResourceId)).ToList();
            }

            if (balancesListView.SelectedUnits != null && balancesListView.SelectedUnits.Count() > 0)
            {
                balances = balances.Where(b => balancesListView.SelectedUnits.Contains(b.UnitId)).ToList();
            }

            foreach (var balance in balances)
            {
                balance.Resource = resources.SingleOrDefault(r => r.Id == balance.ResourceId);
                balance.Unit = units.SingleOrDefault(u => u.Id == balance.UnitId);
            }

            var vm = new BalancesListViewModel
            {
                Balances = balances,
                Resources = resources.Select(r => new SelectListItem
                {
                    Text = r.Title,
                    Value = r.Id.ToString()
                }),
                Units = units.Select(u => new SelectListItem 
                {
                    Text = u.Title,
                    Value = u.Id.ToString()
                }),
                SelectedResources = balancesListView.SelectedResources ?? new List<int>(),
                SelectedUnits = balancesListView.SelectedUnits ?? new List<int>()
            };

            return View(vm);

        }
    }
}

Warehouse.Web/Controllers/ClientController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Warehouse.Domain.Entities;
using Warehouse.Domain.ViewModels.Client;

namespace Warehouse.Web.Controllers
{
    public class ClientController : Controller
    {
        private readonly ILogger<ClientController> _logger;
        private readonly IMemoryCache _memoryCache;

        public ClientController(ILogger<ClientController> logger, IMemoryCache memoryCache)
        {
            _logger = logger;
            _memoryCache = memoryCache;
        }

        public async Task<IActionResult> Index()
        {
            //UoW GetAll
            var clients = _memoryCache.Get<List<Client>>("Clients") ?? new List<Client>();
            var vm = new ClientsListViewModel() { Clients = clients.Where(x => x.IsActive).ToList() };
            return View(vm);


        }

        public async Task<IActionResult> Archive()
        {
            var clients = _memoryCache.Get<List<Client>>("Clients") ?? new List<Client>();
            var vm = new ClientsListViewModel() { Clients = clients.Where(x => !x.IsActive).ToList() };
            return View(vm);
        }
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Title,Address")] Client client)
        {
            var clients = _memoryCache.Get<List<Client>>("Clients") ?? new List<Client>();

            try
            {
                if (ModelState.IsValid)
                {
                    clients.Add(new Client()
                    {
                        Id = clients.Count() + 1,
                        Title = client.Title,
                        Address = client.Address,
                        IsActive = true
                    });
                    _memoryCache.Set("Clients", clients);
                    TempData["Success"] = "Новый клиент успешно добавлен.";
                    return RedirectToAction(nameof(Index));
                }
            }
            catch
            {
                ModelState.AddModelError(string.Empty, "Произошла ошибка!");
            }

            return View();
        }

        public async Task<IActionResult> Edit(int id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            //UoW Get
            var clients = _memoryCache.Get<List<Client>>("Clients") ?? new List<Client>();
            var cli = clients.FirstOrDefault(x => x.Id == id);

            if (cli == null)
            {
                return NotFound();
            }
            return View(cli);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Address")] Client client)
        {
            if (id != client.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var clients = _memoryCache.Get<List<Client>>("Clients") ?? new List<Client>();
                    var cli = clients.FirstOrDefault(x => x.Id == id);
                    if (cli is not null)
                    {
                        cli.Title = client.Title;
                        cli.Address = client.Address;
                    }
                    _memoryCache.Set("Clients", clients);
                    TempData["Success"] = "Клиент успешно отредактирован.";

                }
                catch (Exception)
                {
                    throw;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(client);
        }

        public async Task<IActionResult> EditArchived(int id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            //UoW Get
            var clients = _memoryCache.Get<List<Client>>("Clients") ?? new List<Client>();
            var vm = clients.FirstOrDefault(x => x.Id == id);

            if (vm == null)
            {
                return NotFound();
            }
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> ChangeStatus(int id)
        {
            var clients = _memoryCache.Get<List<Client>>("Clients") ?? new List<Client>();

            try
            {
                var cli = clients.FirstOrDefault(x => x.Id == id);
                if (cli is not null)
                {
                    cli.IsActive = !cli.IsActive;
                }
                _memoryCache.Set("Clients", clients);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction(nameof(Index));
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var clients = _memoryCache.Get<List<Client>>("Clients") ?? new List<Client>();
            try
            {
                var cli = clients.FirstOrDefault(x => x.Id == id);
                if (cli is not null) clients.Remove(cli);

                _memoryCache.Set("Clients", clients);
                TempData["Success"] = "Клиент успешно удален.";
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction(nameof(Index));
            }
        }
    }
}

Warehouse.Web/Controllers/UnitController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Warehouse.Domain.Entities;
using Warehouse.Domain.ViewModels.Unit;

namespace Warehouse.Web.Controllers
{
    public class UnitController : Controller
    {
        private readonly ILogger<UnitController> _logger;
        private readonly IMemoryCache _memoryCache;

        public UnitController(ILogger<UnitController> logger, IMemoryCache memoryCache)
        {
            _logger = logger;
            _memoryCache = memoryCache;
        }

        public async Task<IActionResult> Index()
        {
            //UoW GetAll
            var units = _memoryCache.Get<List<Unit>>("Units") ?? new List<Unit>();
            var vm = new UnitsListViewModel() { Units = units.Where(x => x.IsActive).ToList() };
            return View(vm);


        }

        public async Task<IActionResult> Archive()
        {
            var units = _memoryCache.Get<List<Unit>>("Units") ?? new List<Unit>();
            var vm = new UnitsListViewModel() { Units = units.Where(x => !x.IsActive).ToList() };
            return View(vm);
        }
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Title")] Unit unit)
        {
            var units = _memoryCache.Get<List<Unit>>("Units") ?? new List<Unit>();

            try
            {
                if (ModelState.IsValid)
                {
                    units.Add(new Unit()
                    {
                        Id = units.Count() + 1,
                        Title = unit.Title,
                        IsActive = true
                    });
                    _memoryCache.Set("Units", units);
                    TempData["Success"] = "Новая единица измерения успешно добавлена.";
                    return RedirectToAction(nameof(Index));
                }
            }
            catch
            {
                ModelState.AddModelError(string.Empty, "Произошла ошибка!");
            }

            return View();
        }

        public async Task<IActionResult> Edit(int id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            //UoW Get
            var units = _memoryCache.Get<List<Unit>>("Units") ?? new List<Unit>();
            var vm = units.FirstOrDefault(x => x.Id == id);

            if (vm == null)
            {
                return NotFound();
            }
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title")] Unit unit)
        {
            if (id != unit.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var units = _memoryCache.Get<List<Unit>>("Units") ?? new List<Unit>();
                    var un = units.FirstOrDefault(x => x.Id == id);
                    if (un is not null)
                    {
                        un.Title = unit.Title;
                    }
                    _memoryCache.Set("Units", units);
                    TempData["Success"] = "Единица измерения успешно отредактирована.";

                }
                catch (Exception)
                {
                    throw;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(unit);
        }

        public async Task<IActionResult> EditArchived(int id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            //UoW Get
            var units = _memoryCache.Get<List<Unit>>("Units") ?? new List<Unit>();
            var vm = units.FirstOrDefault(x => x.Id == id);

            if (vm == null)
            {
                return NotFound();
            }
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> ChangeStatus(int id)
        {
            var units = _memoryCache.Get<List<Unit>>("Units") ?? new List<Unit>();

            try
            {
                var unit = units.FirstOrDefault(x => x.Id == id);
                if (unit is not null)
                {
                    unit.IsActive = !unit.IsActive;
                }

                _memoryCache.Set("Units", units);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction(nameof(Index));
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var units = _memoryCache.Get<List<Unit>>("Units") ?? new List<Unit>();
            try
            {
                var unit = units.FirstOrDefault(x => x.Id == id);
                if (unit is not null) units.Remove(unit);

                _memoryCache.Set("Units", units);
                TempData["Success"] = "Единица измерения успешно удалена.";
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction(nameof(Index));
            }
        }
    }
}

Warehouse.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"] - Управление складом</title>
    <partial name="_StylesheetPartial"/>
</head>

<body>
    <div class="container-fluid">
        <div class="row">
            <nav class="sidebar col-12 col-sm bg-dark p-3 sticky-top">
                <div class="mb-3 px-2">
                    <a class="text-light text-decoration-none text-truncate" href="@Url.Action("Index", "Home")">Управление складом</a>
                </div>
                <ul class="nav nav-pills flex-column px-2">
                    <li class="fw-bold text-light mb-3">Склад</li>
                    <li class="mb-3">
                        <a class="d-block text-decoration-none text-light px-2 link__hover" asp-controller="Balance" asp-action="Index">Баланс</a>
                    </li>
                    <li class="mb-3">
                        <a class="d-block text-decoration-none text-light px-2 link__hover" asp-controller="Receipt" asp-action="Index">Поступления</a>
                    </li>
                    <li class="mb-3">
                        <a class="d-block text-decoration-none text-light px-2 link__hover" asp-controller="Shipment" asp-action="Index">Отгрузки</a>
                    </li>
                    <li class="fw-bold text-light mb-3">Справочники</li>
                    <li class="mb-3">
                        <a class="d-block text-decoration-none text-light px-2 link__hover" asp-controller="Client" asp-action="Index">Клиенты</a>
                    </li>
                    <li class="mb-3">
                        <a class="d-block text-decoration-none text-light px-2 link__hover text-truncate" asp-controller="Unit" asp-action="Index">Единицы измерения</a>
                    </li>
                    <li class="mb-3">
                        <a class="d-block text-decoration-none text-light px-2 link__hover" asp-controller="Resource" asp-action="Index">Ресурсы</a>
                    </li>
                </ul>
            </nav>
            <main class="col-12 col-sm bg-secondary text-break p-3">
                <div>
                    <partial name="_Notification"/>
                    @RenderBody()
                </div>
            </main>
        </div>
    </div>  
    <partial name="_ScriptsPartial" />
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Warehouse.Web/Views/Shared/_Notification.cshtml
@if(TempData["Success"] != null){
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
	<script type="text/javascript">
		toastr.success('@TempData["Success"]');
	</script>
}

@if(TempData["Error"] != null){
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
	<script type="text/javascript">
		toastr.error('@TempData["Error"]');
	</script>
}

Warehouse.Web/Views/Shared/_ScriptsPartial.cshtml
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta2/dist/js/bootstrap-select.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>

Warehouse.Web/Views/Shared/_StylesheetPartial.cshtml
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
<link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
<link rel="stylesheet" href="~/Warehouse.Web.styles.css" asp-append-version="true"/>
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"/>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta2/dist/css/bootstrap-select.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css"/>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css">