Warehouse.Web/Controllers/ResourceController.cs
using Microsoft.AspNetCore.Mvc;
using Warehouse.Domain.ViewModels.Resource;
using Microsoft.Extensions.Caching.Memory;
using Warehouse.Domain.Entities;

namespace Warehouse.Web.Controllers
{
    public class ResourceController : Controller
    {
        private readonly ILogger<ResourceController> _logger;
        private readonly IMemoryCache _memoryCache;

        public ResourceController(ILogger<ResourceController> logger, IMemoryCache memoryCache)
        {
            _logger = logger;
            _memoryCache = memoryCache;
        }

        public async Task<IActionResult> Index()
        {
            //UoW GetAll
            var resources = _memoryCache.Get<List<Resource>>("Resources") ?? new List<Resource>();
            var vm = new ResourcesListViewModel() { Resources = resources.Where(x => x.IsActive).ToList() };
            return View(vm);


        }

        public async Task<IActionResult> Archive()
        {
            var resources = _memoryCache.Get<List<Resource>>("Resources") ?? new List<Resource>();
            var vm = new ResourcesListViewModel() { Resources = resources.Where(x => !x.IsActive).ToList() };
            return View(vm);
        }
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Title")] Resource resource)
        {
            var resources = _memoryCache.Get<List<Resource>>("Resources") ?? new List<Resource>();

            try
            {
                if (ModelState.IsValid)
                {
                    resources.Add(new Resource()
                    {
                        Id = resources.Count() + 1,
                        Title = resource.Title,
                        IsActive = true
                    });
                    _memoryCache.Set("Resources", resources);
                    TempData["Success"] = "Новый ресурс успешно добавлен.";
                    return RedirectToAction(nameof(Index));
                }
            }
            catch
            {
                ModelState.AddModelError(string.Empty, "Произошла ошибка!");
            }

            return View();
        }

        public async Task<IActionResult> Edit(int id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            //UoW Get
            var resources = _memoryCache.Get<List<Resource>>("Resources") ?? new List<Resource>();
            var vm = resources.FirstOrDefault(x => x.Id == id);

            if (vm == null)
            {
                return NotFound();
            }
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title")] Resource resource)
        {
            if (id != resource.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var resources = _memoryCache.Get<List<Resource>>("Resources") ?? new List<Resource>();
                    var res = resources.FirstOrDefault(x => x.Id == id);
                    if (res is not null)
                    {
                        res.Title = resource.Title;
                    }
                    _memoryCache.Set("Resources", resources);
                    TempData["Success"] = "Ресурс успешно отредактирован.";

                }
                catch (Exception)
                {
                    throw;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(resource);
        }

        public async Task<IActionResult> EditArchived(int id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            //UoW Get
            var resources = _memoryCache.Get<List<Resource>>("Resources") ?? new List<Resource>();
            var vm = resources.FirstOrDefault(x => x.Id == id);

            if (vm == null)
            {
                return NotFound();
            }
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> ChangeStatus(int id)
        {
            var resources = _memoryCache.Get<List<Resource>>("Resources") ?? new List<Resource>();

            try
            {
                var res = resources.FirstOrDefault(x => x.Id == id);
                if (res is not null)
                {
                    res.IsActive = !res.IsActive;
                }
                _memoryCache.Set("Resources", resources);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction(nameof(Index));
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var resources = _memoryCache.Get<List<Resource>>("Resources") ?? new List<Resource>();
            try
            {
                var res = resources.FirstOrDefault(x => x.Id == id);
                if (res is not null) resources.Remove(res);

                _memoryCache.Set("Resources", resources);
                TempData["Success"] = "Ресурс успешно удален.";
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction(nameof(Index));
            }
        }
    }
}

Warehouse.Web/Views/Resource/Archive.cshtml
@model Warehouse.Domain.ViewModels.Resource.ResourcesListViewModel

@{
    ViewData["Title"] = "Ресурсы";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <h2 class="text-dark text-truncate">@ViewData["Title"]</h2>
            <a asp-controller="Resource" asp-action="Index" class="btn btn-dark link__hover text-truncate me-2 mb-2">К рабочим</a>
        </div>
    </div>
    <br>

    @if (Model.Resources is not null && Model.Resources.Count() > 0)
    {
        <table class="table table-hover border border-dark w-100">
            <thead>
                <tr>
                    <th class="text-truncate" scope="col">
                        @Html.DisplayName("Наименование")
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var resource in Model.Resources)
                {
                    <tr>
                        <td class="text-truncate">
                            <a asp-controller="Resource" asp-action="EditArchived" asp-route-id="@resource.Id" class="d-block text-decoration-none text-reset">@Html.DisplayFor(modelItem => resource.Title)</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>Список ресурсов пуст!</p>
    }
</div>

Warehouse.Web/Views/Resource/Create.cshtml
@model Warehouse.Domain.Entities.Resource

@{
    ViewData["Title"] = "Ресурс";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <h2 class="text-dark text-truncate">@ViewData["Title"]</h2>
            <div class="d-flex flex-wrap flex-sm-nowrap">
                <button type="submit" form="createForm" class="btn btn-dark link__hover text-truncate me-2 mb-2">Сохранить</button>
                <a asp-action="Index" class="btn btn-dark link__hover text-truncate me-2 mb-2">Назад к списку</a>
            </div>
            <br>
            <form id="createForm" method="post" asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Title" class="control-label w-100 text-truncate"></label>
                    <input asp-for="Title"/>
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Warehouse.Web/Views/Resource/Edit.cshtml
@model Warehouse.Domain.Entities.Resource

@{
    ViewData["Title"] = "Ресурс";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <h2 class="text-dark text-truncate">@ViewData["Title"]</h2>
            <div class="d-flex flex-wrap flex-sm-nowrap">
                <button type="submit" form="editForm" class="btn btn-dark link__hover text-truncate me-2 mb-2">Сохранить</button>
                <form method="post" asp-action="Delete" class="me-2 mb-2">
                    <input type="hidden" asp-for="Id"/>
                    <button type="submit" class="btn btn-dark link__hover text-truncate" onclick="return confirm('Вы уверены?')">Удалить</button>
                </form>
                <form method="post" asp-action="ChangeStatus" class="me-2 mb-2">
                    <input type="hidden" asp-for="Id"/>
                    <button type="submit" class="btn btn-dark link__hover text-truncate">В архив</button>
                </form>
                <a asp-action="Index" class="btn btn-dark link__hover text-truncate me-2 mb-2">Назад к списку</a>
            </div>
            <br>
            <form id="editForm" method="post" asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id"/>
                <div class="form-group">
                    <label asp-for="Title" class="control-label w-100 text-truncate"></label>
                    <input asp-for="Title"/>
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Warehouse.Web/Views/Resource/EditArchived.cshtml
@model Warehouse.Domain.Entities.Resource

@{
    ViewData["Title"] = "Ресурс";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <h2 class="text-dark text-truncate">@ViewData["Title"]</h2>
            <div class="d-flex flex-wrap flex-sm-nowrap">
                <button type="submit" form="editForm" class="btn btn-dark link__hover text-truncate me-2 mb-2">Сохранить</button>
                <form method="post" asp-action="Delete" class="me-2 mb-2">
                    <input type="hidden" asp-for="Id" />
                    <button type="submit" class="btn btn-dark link__hover text-truncate" onclick="return confirm('Вы уверены?')">Удалить</button>
                </form>
                <form method="post" asp-action="ChangeStatus" class="me-2 mb-2">
                    <input type="hidden" asp-for="Id" />
                    <button type="submit" class="btn btn-dark link__hover text-truncate">В работу</button>
                </form>
                <a asp-action="Index" class="btn btn-dark link__hover text-truncate me-2 mb-2">Назад к списку</a>
            </div>
            <br>
            <form id="editForm" method="post" asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <div class="form-group">
                    <label asp-for="Title" class="control-label w-100 text-truncate"></label>
                    <input asp-for="Title"/>
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Warehouse.Web/Views/Resource/Index.cshtml
@model Warehouse.Domain.ViewModels.Resource.ResourcesListViewModel

@{
    ViewData["Title"] = "Ресурсы";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <h2 class="text-dark text-truncate">@ViewData["Title"]</h2>
            <div class="d-flex flex-wrap flex-sm-nowrap">
                <a asp-controller="Resource" asp-action="Create" class="btn btn-dark link__hover text-truncate me-2 mb-2">Добавить</a>
                <a asp-controller="Resource" asp-action="Archive" class="btn btn-dark link__hover text-truncate me-2 mb-2">К архиву</a>
            </div>
        </div>
    </div>
    <br>
    @if (Model.Resources is not null && Model.Resources.Count() > 0)
    {
        <table class="table table-hover border border-dark w-100">
            <thead>
                <tr>
                    <th class="text-truncate" scope="col">
                        @Html.DisplayName("Наименование")
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var resource in Model.Resources)
                {
                    <tr>
                        <td class="text-truncate">
                            <a asp-controller="Resource" asp-action="Edit" asp-route-id="@resource.Id" class="d-block text-decoration-none text-reset">@Html.DisplayFor(modelItem => resource.Title)</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>Список ресурсов пуст!</p>
    }
</div>

Warehouse.Web/Views/Resource/Resources.cshtml
@model Warehouse.Web.Models.Resource.ResourcesListViewModel

@{
    ViewData["Title"] = "Ресурсы";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-6">
            <h2 class="text-dark text-truncate">@ViewData["Title"]</h2>
            <div>
                <a class="btn btn-dark link__hover text-truncate" asp-controller="Resource" asp-action="Add">Добавить</a>
                <a class="btn btn-dark link__hover text-truncate" asp-controller="Resource" asp-action="Archieve">К архиву</a>
            </div>
        </div>
    </div>
    <br>
    <table class="table table-hover border border-dark w-100">
        <thead>
            <tr>
                <th class="text-truncate" scope="col">
                    @Html.DisplayName("Наименование")
                </th>
            </tr>
        </thead>
        <tbody>
            @if (Model.ResourcesList is not null)
            {
                foreach (var resource in Model.ResourcesList)
                {
                    <tr>
                        <td class="text-truncate">
                            @Html.DisplayFor(modelItem => resource.Title)
                        </td>
                    </tr>
                }
            }
            else
            {
                <p>Нет доступных ресурсов.</p>
            }
        </tbody>
    </table>
</div>